### ISSUE TITLE
Songs aren't deduplicated

### ISSUE THREAD

**Issue by alexkau** [Lucretiel/BeachWeekSongList#1]
```
10691   Blackout    (HED) Planet Earth  TriceraSoft.xml
10692   Blackout    (HED) Planet Earth  TriceraSoft.xml
40395   Other Side  (Hed) Planet Earth  TriceraSoft.xml
40396   Other Side  (Hed) Planet Earth  TriceraSoft.xml
```

Deduplication of songs on (title, artist, source) would be useful.

**Comment by Lucretiel** [comment]
Currently they're deduplicated by the song ID (see https://github.com/Lucretiel/BeachWeekSongList/blob/master/parse_song_lists.py and https://github.com/Lucretiel/BeachWeekSongList/tree/master/songs). Will look into adding an extra dedupe by song+artist+source.
